# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI - integration tests

on:
  pull_request:
    paths-ignore:
      - "doc/**"
      - ".github/**"
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - ".prettierrc*"
    branches:
      - main
  workflow_dispatch: # Enables manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: |
          # Download config.json
          gist_id="ab0825c2949cf39b082e66aa0b39453a"
          file_name="integration-tests.config.json"
          url="https://gist.githubusercontent.com/${{ github.repository_owner }}/${gist_id}/raw/${file_name}"
          curl -o config.json $url
          cat ./config.json
      - run: |
          # Write token files
          echo ${{ secrets.ITEST_AIRTABLE_TOKEN }} > ~/airtable.token
          echo ${{ secrets.ITEST_GITHUB_TOKEN }} > ~/github.token
      - run: npm run test:integration
