name: CI - pr merge to main

on:
  pull_request:
    types:
      - closed

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Fire new_release event if PR is merged
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const action = context.payload.action;
            console.log(`pr.merged: ${pr.merged}, action: ${action}`);
            if (!pr.merged) {
              return;
            }

            const excludedPrefixes = ['ci', 'skip ci', 'doc'];
            if (excludedPrefixes.some(prefix => pr.title.toLowerCase().startsWith(`[${prefix}]`))) {
              return;
            }

            // Fire a new_release event to trigger the release job
            const response = await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'new_release',
              client_payload: {
                prNumber: context.payload.number,
                branch,
              }
            });
