name: CI - pr merge to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from release branch
        if: startsWith(github.ref, 'refs/heads/release/v')
        uses: actions/github-script@v7
        with:
          script: |
            const ref = github.ref; // Example: refs/heads/release/v1.0.0
            const branch = ref.split('/').slice(2).join('/'); // Extract branch name (e.g., release/v1.0.0)
            const tagName = `${branch.split('/')[1]}`; // Assuming release/v1.0.0 -> v1.0.0
            console.log(`Branch: ${branch}`);
            console.log(`Tag Name: ${tagName}`);
            
            // Fetch remote tags
            const { data: remoteTags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const tagExists = remoteTags.some(tag => tag.name === tagName);

            if (!tagExists) {
              core.setFailed(`Tag ${tagName} has not been pushed to the remote repository.`);
            }

            // Fire a new_release event to trigger the release job
            const response = await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'new_release',
              client_payload: {
                prNumber: context.payload.pull_request?.number,
                prTitle: context.payload.pull_request?.title,
                branch: github.head_ref,
              }
            });
