name: CI - pr merge to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from release branch
        if: startsWith(github.head_ref, 'release/')
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'new_release',
              payload: {
                prNumber: context.payload.pull_request?.number,
                prTitle: context.payload.pull_request?.title,
                branch: github.head_ref,
              }
            });
