name: CI - pr merge to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from release branch
        if: startsWith(github.head_ref, 'release/v')
        uses: actions/github-script@v7
        with:
          script: |
            const branch = github.head_ref;
            const tagName = `${branch.split('/')[1]}`; // Assuming tag follows the release branch naming convention (e.g., release/1.0.0 -> v1.0.0)

            // Fetch remote tags
            const { data: remoteTags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const tagExists = remoteTags.some(tag => tag.name === tagName);

            if (!tagExists) {
              core.setFailed(`Tag ${tagName} has not been pushed to the remote repository.`);
            }

            // Fire a new_release event to trigger the release job
            const response = await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'new_release',
              client_payload: {
                prNumber: context.payload.pull_request?.number,
                prTitle: context.payload.pull_request?.title,
                branch: github.head_ref,
              }
            });
